### ISSUE TITLE
Update raster exporter to also support COG (cloud optimized GeoTIFF)

### ISSUE THREAD

**Issue by neteler** [mundialis/actinia_core#106]
In the raster exporter currently there are hardcoded GeoTIFF settings:

https://github.com/mundialis/actinia_core/blob/8353b231c1a475955f68e4484e329c7d74b292e0/src/actinia_core/resources/ephemeral_processing_with_export.py#L251

Since GDAL 3.1+ there is a new [COG](https://gdal.org/drivers/raster/cog.html) driver which works nicely with `r.out.gdal`.

Wish: add `COG` driver support and use it if present. This would require a test:

```
r.out.gdal -l
  COG (rw): Cloud optimized GeoTIFF generator
```

- if `COG` driver present, use it for `r.out.gdal` export:
    - `r.out.gdal -m input=mymap output=mymap.tif format=COG`
- if `COG` driver not present, use the current GeoTIFF based `r.out.gdal` export.

**Comment by mmacata** [comment]
Isn't this implemented by https://github.com/mundialis/actinia_core/pull/108 ?

**Comment by neteler** [comment]
Yes - the PR wasn't linked.
