### ISSUE TITLE
Building and deployment of actinia_core

### ISSUE THREAD

**Issue by geography** [mundialis/actinia_core#119]
Hi all, 
when I try to build and deploy actinia_core in a docker container I get the following error message: 

Starting GRASS GIS...
ERROR: Unable to create new location because the location <utm32n> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <latlong_wgs84> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <nc_spm_08> already exists.
Exiting...
/src/start.sh: line 29: actinia-user: not found
/src/start.sh: line 30: actinia-user: not found
Failed to start actinia-user: 127
Starting GRASS GIS...
ERROR: Unable to create new location because the location <utm32n> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <latlong_wgs84> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <nc_spm_08> already exists.
Exiting...
/src/start.sh: line 29: actinia-user: not found
/src/start.sh: line 30: actinia-user: not found
Failed to start actinia-user: 127
Starting GRASS GIS...
ERROR: Unable to create new location because the location <utm32n> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <latlong_wgs84> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <nc_spm_08> already exists.
Exiting...
/src/start.sh: line 29: actinia-user: not found
/src/start.sh: line 30: actinia-user: not found
Failed to start actinia-user: 127
Starting GRASS GIS...
ERROR: Unable to create new location because the location <utm32n> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <latlong_wgs84> already exists.
Exiting...
Starting GRASS GIS...
ERROR: Unable to create new location because the location <nc_spm_08> already exists.
Exiting...
/src/start.sh: line 29: actinia-user: not found
/src/start.sh: line 30: actinia-user: not found
Failed to start actinia-user: 127

Someone can give me some hint to try to solve it? 
Thanks in advance for all the work done.
Ema.

**Comment by neteler** [comment]
Please tell us a bit more how you actually build and deploy actinia_core in a docker container.

**Comment by geography** [comment]
Hi Markus, 

I tried this in my windows 10 work environment:

**1) I opened a cmd line with powershell
2) git clone https://github.com/mundialis/actinia_core.git
3) cd actinia_core/docker/
4) docker-compose -f docker-compose-dev.yml build
5) docker-compose -f docker-compose-dev.yml up**

and the output was:

PS C:\Work\Code\actinia_core\docker> docker-compose -f docker-compose-dev.yml up
Starting docker_redis_1 ... done
Recreating docker_actinia_1 ... done
Attaching to docker_redis_1, docker_actinia_1
actinia_1  | Starting GRASS GIS...
actinia_1  | ERROR: Unable to create new location because the location <utm32n> already exists.
actinia_1  | Exiting...
actinia_1  | Starting GRASS GIS...
actinia_1  | ERROR: Unable to create new location because the location <latlong_wgs84> already exists.
actinia_1  | Exiting...
actinia_1  | Starting GRASS GIS...
actinia_1  | ERROR: Unable to create new location because the location <nc_spm_08> already exists.
redis_1    | 1:C 22 Oct 2020 07:57:48.559 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 22 Oct 2020 07:57:48.561 # Redis version=5.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 22 Oct 2020 07:57:48.561 # Configuration loaded
redis_1    |                 _._
redis_1    |            _.-``__ ''-._
redis_1    |       _.-``    `.  `_.  ''-._           Redis 5.0.4 (00000000/0) 64 bit
redis_1    |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1    |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1    |   `-._    `-._  `-./  _.-'    _.-'
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1    |  |    `-._`-._        _.-'_.-'    |
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1    |       `-._    `-.__.-'    _.-'
redis_1    |           `-._        _.-'
redis_1    |               `-.__.-'
redis_1    |
redis_1    | 1:M 22 Oct 2020 07:57:48.567 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 22 Oct 2020 07:57:48.567 # Server initialized
redis_1    | 1:M 22 Oct 2020 07:57:48.567 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
actinia_1  | Exiting...
actinia_1  | /src/start.sh: line 29: actinia-user: not found
actinia_1  | /src/start.sh: line 30: actinia-user: not found
redis_1    | 1:M 22 Oct 2020 07:57:48.576 * DB loaded from disk: 0.009 seconds
redis_1    | 1:M 22 Oct 2020 07:57:48.576 * Ready to accept connections
actinia_1  | Failed to start actinia-user: 127
docker_actinia_1 exited with code 127

Thanks a lot for any hint,
Ema.

**Comment by geography** [comment]
Hi Markus,

actually I have this status on my container:

![image](https://user-images.githubusercontent.com/1279559/97155522-c6de4500-1775-11eb-8aa9-8d224d3e1f9d.png)

and on the docker_actinia_1 I have this status with this error:

![image](https://user-images.githubusercontent.com/1279559/97155698-086ef000-1776-11eb-9be5-4693a62a645e.png)

**Comment by ajay3379** [comment]
Hi Markus,
I am also facing the same issue when I try to install on my windows 10 local desktop using docker-compose-dev.yml file
I get the error as per screenshot.
![Error1](https://user-images.githubusercontent.com/15335222/97181424-3a17a380-17d6-11eb-95de-f7c2c0ba6193.PNG)
Looks like its failing under User Creation

**Comment by neteler** [comment]
I can confirm it:

```
git clone https://github.com/mundialis/actinia_core.git
cd actinia_core/docker/

sudo docker-compose -f docker-compose-dev.yml build
redis uses an image, skipping
Building actinia
...
Successfully built c9d6a0811c51
Successfully tagged docker_actinia:latest

sudo docker-compose -f docker-compose-dev.yml up
Creating network "docker_default" with the default driver
Creating docker_redis_1 ... done
Creating docker_actinia_1 ... done
Attaching to docker_redis_1, docker_actinia_1
actinia_1  | Starting GRASS GIS...
redis_1    | 1:C 26 Oct 2020 16:24:40.342 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
...
redis_1    | 1:M 26 Oct 2020 16:24:40.345 * Ready to accept connections
actinia_1  | Creating new GRASS GIS location <utm32n>...
actinia_1  | Cleaning up temporary files...
actinia_1  | Cleaning up temporary files...
actinia_1  | Starting GRASS GIS...
actinia_1  | Creating new GRASS GIS location <latlong_wgs84>...
actinia_1  | Cleaning up temporary files...
actinia_1  | Cleaning up temporary files...
actinia_1  | Starting GRASS GIS...
actinia_1  | Creating new GRASS GIS location <nc_spm_08>...
actinia_1  | Cleaning up temporary files...
actinia_1  | Cleaning up temporary files...
actinia_1  | /src/start.sh: line 29: actinia-user: not found
actinia_1  | /src/start.sh: line 30: actinia-user: not found
actinia_1  | Failed to start actinia-user: 127
```

Since the script is here:
https://github.com/mundialis/actinia_core/blob/master/scripts/actinia-user

I assume that it is a path issue in the docker file, to be fixed.

**Comment by mmacata** [comment]
Hi all, a `python3 setup.py install` is missing. We adjusted the dev setup a while ago to enter the running container and mount the source code locally. We forgot to update the README accordingly - sorry for that. I added the missing pieces: https://github.com/mundialis/actinia_core/pull/122
Please tell me, if it is working for you.

**Comment by ajay3379** [comment]
Hi mmacata,

Below command works as expected :
# or DEV setup
docker-compose -f docker-compose-dev.yml build
docker-compose -f docker-compose-dev.yml run --service-ports --entrypoint sh actinia

![image](https://user-images.githubusercontent.com/15335222/97310760-8fb78300-189e-11eb-8aee-c326c1e09ec7.png)

then we can see docker containers are running...
After I have tried to run python3 setup.py install then I get following error 
![image](https://user-images.githubusercontent.com/15335222/97310993-d3aa8800-189e-11eb-9d17-e548969d1f7a.png)

**Comment by mmacata** [comment]
Hi ajay3379, this error usually appears, when no version can be detected. When a `.git` folder is present, the version can be taken out of it. Did you get the actinia source code by running `git clone` ? Then you can run `docker exec -it eb python3 ls -lah` with your container ID and see, if the `.git` folder is listed. In my case, it looks like this:
```
09:23 $ docker exec -it eb ls -lah
total 212K   
drwxr-xr-x   11 1000     1000        4.0K Oct 27 10:31 .
drwxr-xr-x    1 root     root        4.0K Oct 17 15:47 ..
-rw-r--r--    1 1000     1000         551 Feb 19  2020 .coveragerc
-rw-rw-r--    1 1000     1000         485 Oct 27 10:31 .dockerignore
drwxr-xr-x    3 root     root        4.0K Oct 27 08:50 .eggs
drwxr-xr-x    8 1000     1000        4.0K Oct 28 08:23 .git
-rw-rw-r--    1 1000     1000         872 Oct 27 10:31 .gitignore
-rw-r--r--    1 1000     1000         206 Feb 19  2020 AUTHORS.rst
-rw-r--r--    1 1000     1000         128 Feb 19  2020 CHANGELOG.rst
-rw-r--r--    1 1000     1000        7.6K Feb 19  2020 CONTRIBUTING.md
-rw-r--r--    1 1000     1000       31.7K Feb 19  2020 LICENSE.txt
-rw-rw-r--    1 1000     1000         249 Oct 27 10:31 Makefile
-rw-rw-r--    1 1000     1000        3.5K Sep 23 12:31 README.md
-rw-r--r--    1 root     root        3.0K May  7 14:54 actinia-gdi.log
-rw-r--r--    1 1000     1000        1.2K Feb 19  2020 actinia.cfg
drwxr-xr-x    5 root     root        4.0K Sep 30 11:56 build
-rw-r--r--    1 1000     1000        4.7K Jan 30  2020 dev
drwxr-xr-x    2 root     root        4.0K Oct 28 08:23 dist
drwxr-xr-x    9 1000     1000        4.0K Oct 27 10:31 docker
drwxr-xr-x    3 1000     1000        4.0K Sep 23 14:51 docs
-rw-rw-r--    1 1000     1000       16.7K Jun  3 14:29 logging.md
-rw-rw-r--    1 1000     1000        1.1K Sep 23 12:31 requirements-alpine.txt
-rw-rw-r--    1 1000     1000         736 Jun  3 14:29 requirements.txt
-rw-rw-r--    1 1000     1000         671 Sep 23 12:31 requirements_ubuntu19.txt
drwxr-xr-x    4 1000     1000        4.0K Sep 23 12:31 scripts
-rw-r--r--    1 1000     1000        2.3K Feb 19  2020 setup.cfg
-rw-r--r--    1 1000     1000        2.0K Feb 19  2020 setup.py
drwxr-xr-x    4 1000     1000        4.0K Sep 30 11:56 src
drwxr-xr-x    3 1000     1000        4.0K Oct 27 10:31 tests
-rw-rw-r--    1 1000     1000         250 Oct 27 10:31 tests_with_redis.sh
```
If the `.git` folder is missing, the mount into the docker container was not successful and I wouldn't have a clue, why this is the case, if other folders + files were mounted correctly. Maybe it somehow depends on the operating system and hidden files !?

Another possibility to set the version is to add `ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.99.13` to `docker/actinia-core-dev/Dockerfile`. It wouldn't affect runtime, it only makes it hard to compare versions from `/api/v1/version` endpoint. Depending on working state they usually look something like `0.99.13.post0.dev26+g98dd584`.

Hope, this helps!

**Comment by geography** [comment]
Hi all,

this is my status on the container now:

![image](https://user-images.githubusercontent.com/1279559/97580351-770cb180-19f3-11eb-954e-1ebb07bc3612.png)

The 2 containers are up and running.
Now I have to play with it a little, if I encounter further problems I will notify you promptly.

Thanks again for the great job done,
Ema.

**Comment by ajay3379** [comment]
I also confirm that its working as expected.
Thanks mmacata  for pointing in the right direction.

Regards
Ajay
