### ISSUE TITLE
VOLUME /grassdb vs /actinia_core/grassdb?

### ISSUE THREAD

**Issue by neteler** [mundialis/actinia_core#135]
There is an empty `/grassdb/` in the deployed docker container while data really reside in `/actinia_core/grassdb/`.

Perhaps a wrong path here?

https://github.com/mundialis/actinia_core/blob/fdc0d91d83a528a0584cf206f701a057ba01bb6d/docker/actinia-core-alpine/Dockerfile#L142

Maybe the purpose is something else - then just disregard this issue.

**Comment by mmacata** [comment]
We don't use it in our deployment but it might be useful for other users to have a persistent volume inside the docker container. As it doesn't disturb or add size to the image, we keep it.
