### ISSUE TITLE
new script headers for actinia

### ISSUE THREAD

**Issue by tilladams** [mundialis/actinia_core#14]
In order to get actinia_core under the umbrella of OSGeo as an OSGeo community project, we need to replace the script headers. The license of actinia (GPL 3) must be mentioned. I suggest s.th. like the GRASS team does:

/*!
    \ SOME COMMENT  
  (C) 2018 by the actinia Development Team
  
  This program is free software under the GNU General Public License
  (>=v3). Read the file COPYING that comes with actinia for details.
  
  \ MAYBE AUTHOR
*/

**Comment by marcjansen** [comment]
See #9

**Comment by neteler** [comment]
Closed as duplicate
