### ISSUE TITLE
Should we move "ace (actinia command execution)" to a dedicated repository?

### ISSUE THREAD

**Issue by marcjansen** [mundialis/actinia_core#151]
I think we should move `ace` to a dedicated repository, as it is a IMO utility that helps working with actinia instances.

Or is it a central part of actinia, without which actinia isn't fulfilling it's central goal?

What do you think?

**Comment by neteler** [comment]
Yes, we have done that, see https://github.com/mundialis/ace

**Comment by marcjansen** [comment]
Ok, cool. It looks as if there is still ace code in the scripts folder? I might be misunderstanding stuff...

**Comment by neteler** [comment]
Overall: yes, the copy of the `ace` script here may be removed in favour of the new-ish repo
