### ISSUE TITLE
Feature Request: Add Dockerfiles to enhance development workflow

### ISSUE THREAD

**Issue by cwhite911** [mundialis/actinia_core#16]
The barrier of entry [installing](https://actinia.mundialis.de/tutorial/installation.html) and running actinia_core is currently very cumbersome because of the complex development environment.  I want to reduce the barrier of entry [installing](https://actinia.mundialis.de/tutorial/installation.html) the project and its many dependencies by creating Dockerfiles and shell scripts or makefile to build and run actinia_core. Two Dockerfiles could be used to separate the core API and the GRASS sessions [GRASS Dockerfile](https://hub.docker.com/r/neteler/grassgis7/dockerfile), and any other containers could be easily added for storage or caching.

Ideally, a new developer should be able to download the project and start it with one command if they have Docker installed.

For example:
```
make server
```
or 
```
./run.sh
```
I'm willing to work on implementing the new feature, so let me know if first, you all want this and second if you have any other ideas or suggestions of how to best accomplish this task. 

Thanks for all of the hard work!

**Comment by neteler** [comment]
Dockerfiles have been added, please try them out!

**Comment by marcjansen** [comment]
@cwhite911 did you find time to check the Docker files?

**Comment by cwhite911** [comment]
@marcjansen the Docker file and test documentation are working great! Thanks for implementing!

**Comment by neteler** [comment]
You also find a ready-to-use image on docker hub: https://hub.docker.com/r/mundialis/actinia-core
