### ISSUE TITLE
Create endpoint to list all mapsets for every location

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#162]
As a visitor of an actinia instance, it would be helpful to see all connected data, without a filter if I am allowed to use it or not. The current endpoints can list all locations which I am allowed to use or all mapsets of a certain location which I am allowed to use. It would be helpfull to see at one glance which data is available in the whole system.

Edit: it would additionally be helpful to see if the data is in the global grassdb or in the userdb.

**Comment by mmacata** [comment]
I just opened the API docs and checked all topics (https://redocly.github.io/redoc/?url=https://actinia.mundialis.de/api/v1/swagger.json#tag/Mapsets). From all I knew what is behind, except the `Mapsets` one confused my a bit. When you will add this new endpoint, maybe we can think of a name which explains it a bit better, like `Mapsets Lister`, `Mapsets Filter`, ... I cannot make up a great name now, maybe we can think about it then together.

**Comment by griembauer** [comment]
A partial solution is implemented in #249 : A user can get their respective available mapsets from the **global** grassdb. A superadmin can check available mapsets for individual user_ids

**Comment by mmacata** [comment]
Great! Closing this. If we need adjustments, we can create a new ticket later.
