### ISSUE TITLE
Install Issues, (step 2 in directions)

### ISSUE THREAD

**Issue by ahalota** [mundialis/actinia_core#169]
I am trying to set up a local actinia grass server on Linux Mint. It's a new computer with nothing except the basics installed so far.
Specs:
- Operating System: Linux Mint 20.1 Cinnamon v.4.8.6
- Linux Kernel : 5.4.0-66-generic
- Processor: Intel Core i5-2500K CPU @ 3.30GHz x 4
- Memory: 15.6 GiB
- Hard Drives: 1282.4 GB
- Graphics Card: AMD/ATI Tahiti PRO [Radeon HD 7950/8950 OEM/R9 280] (prog-if 00 [VGA controller])

I am following these instructions: https://actinia.mundialis.de/tutorial/installation.html

Step one went mostly well, and step 2 to install grass as well. 

Some minor issues:

- `cd /tmp`
   On my machine, /tmp automatically clears when the computer restarts, so it was not an ideal location. I would not recommend placing the downloads into that folder.
```
make -j16
sudo make install
```
- I had to install a few extra dev libraries for this step to work. The names were in general fairly obvious, always some sort of libdev version of whatever XXX.h file was said to be missing. Here is a list of the ones that I had to install:
    - zlib1g-dev
    - libghc-bzlib-dev
    - libstd-dev
    - libgdal-dev
    - libcairo2-dev

In order to use the grass GUI, located in grass_master/bin.x86_64-pc-linux-gnu/grass78, I also had to install:
   - python3-wxgtk4.0

I am now stuck on trying to make t.rast.sample
```
cd temporal
git clone https://bitbucket.org/huhabla/temporal-raster-sampling.git t.rast.sample
cd t.rast.sample
make
sudo make install
```

It tells me I am missing the library openeo_udf. My best guess for where to find and install this library is here: https://github.com/Open-EO/openeo-udf . Is this correct one? This has a lot of dependencies as well, so I'm running into issues with their makefile that I will post there as well.

**Comment by anikaweinmann** [comment]
Documentation has been improved, closing ticket
