### ISSUE TITLE
Add a project version to the version endpoint

### ISSUE THREAD

**Issue by anikaweinmann** [mundialis/actinia_core#175]
It would be nice to have a possibility to specify a project version which can be seen in the version endpoint. 
Maybe the version can been set via an environment variable and if it is set, it will be displayed by requesting e.g. https://actinia.mundialis.de/api/v1/version. 
It cood look like this:
```
{
      "grass_version": {...},
      "plugin_versions": {...},
      "plugins": "actinia_statistic_plugin,actinia_satellite_plugin,actinia_gdi",
      "project_version": "1.0.0",
      "python_version": "3.8.5 (default, Jul 20 2020, 23:11:29) - [GCC 9.3.0]",
      "version": "0.99.19"
}
```

**Comment by mmacata** [comment]
Might also be nice to add "deployed_since" to see at what date + time a new version was deployed or something like that.

**Comment by marcjansen** [comment]
Is someone working on this atm? I could think of giving this a go, no promise, though.

**Comment by marcjansen** [comment]
Ideas on how to approach this:

- Check a environment variable `ACTINIA_ADDITIONAL_VERSION_INFO`
- if this exists, we'll try to parse the content of it as follows:
  - ACTINIA_ADDITIONAL_VERSION_INFO=key:value;another_key:some other value
  - would lead to 
```
{
      "grass_version": {...},
      "plugin_versions": {...},
      "plugins": "actinia_statistic_plugin,actinia_satellite_plugin,actinia_gdi",
      "python_version": "3.8.5 (default, Jul 20 2020, 23:11:29) - [GCC 9.3.0]",
      "version": "0.99.19",
      "key": "value",
      "another_key": "some other value"
}
```

- values are always strings
- none of the already existing keys (like `version`) can be overridden
- what we cannot parse we ignore.

For the second part of this issue:
- The key `deployed_since` will be added and populated from the environment variable `ACTINIA_DEPLOYED_SINCE`
- inside of `docker/*/start.sh` we'll try to set the environmaentvariable with the current date and time

**Comment by marcjansen** [comment]
WIP PR here: https://github.com/mundialis/actinia_core/pull/252
