### ISSUE TITLE
Transform documentation

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#181]
It would be more feasable to use markdown instead of rst. Therefore it would be good to transform the existing documentation and integrate it into CI, possibly use https://www.mkdocs.org, https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes.
While at it it would be also great to restructure existing documentation (API docs, user docs, docstring, tutorial, ...) to avoid rendundancy.

**Comment by neteler** [comment]
A first 5 min attempt looks promising:

![image](https://user-images.githubusercontent.com/1295172/119729499-063c5380-be75-11eb-87ba-61e279332c32.png)

Certainly a lot of cleanup in the MD files is needed...
