### ISSUE TITLE
Create gource for actinia

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#206]
Like this one :) https://grasswiki.osgeo.org/wiki/GRASS_development_visualization

**Comment by neteler** [comment]
I have a local version almost ready. Where to store script and captions file?

![image](https://user-images.githubusercontent.com/1295172/119826986-ecdceb00-bef8-11eb-8bd5-e8ad354eb8ed.png)

**Comment by mmacata** [comment]
Where do you store it for GRASS GIS? Should we create a new repository for it?

**Comment by neteler** [comment]
> Where do you store it for GRASS GIS?

AFAIR there is no official place so far.

> Should we create a new repository for it?

In #219 I have added it as a subdirectory to `docs/` since a full repo for just one script and a caption file is IMHO too much overhead.

**Comment by mmacata** [comment]
Fine for me!
