### ISSUE TITLE
Check install steps

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#211]
Follow the installation steps from https://actinia.mundialis.de/tutorial/installation.html and document deprecated information in this ticket or directly in the documentation.
Attention: the documentation changed from rst files to md: https://github.com/mundialis/actinia_core/blob/main/docs/docs/installation.md

**Comment by neteler** [comment]
(please feel free to directly edit the new `installation.md` file and propose changes as PR, thanks)

**Comment by sabman** [comment]
@mmacata I'm taking a look at this now for the following distro
```
Linux li1502-8 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

**Comment by sabman** [comment]
I'm running into issues at

**Comment by sabman** [comment]
So I got up to https://github.com/mundialis/actinia_core/blob/main/docs/docs/installation.md?plain=1#L80-L85 after following dependencies where met:

```
apt install zlib1g-dev unzip build-essentials libbz2-dev \
  libzstd-dev gdal-bin libgdal-dev libfftw3-dev libcairo2-dev
```

However the next step is causing the following error. 

```
root@li1502-8:/tmp/grass_master/temporal# cd t.rast.sample/
root@li1502-8:/tmp/grass_master/temporal/t.rast.sample# make
if [ "/tmp/grass_master/dist.x86_64-pc-linux-gnu/scripts/t.rast.sample" != "" ] ; then GISRC=/tmp/grass_master/dist.x86_64-pc-linux-gnu/demolocation/.grassrc78 GISBASE=/tmp/grass_master/dist.x86_64-pc-linux-gnu PATH="/tmp/grass_master/dist.x86_64-pc-linux-gnu/bin:/tmp/grass_master/dist.x86_64-pc-linux-gnu/bin:/tmp/grass_master/dist.x86_64-pc-linux-gnu/scripts:$PATH" PYTHONPATH="/tmp/grass_master/dist.x86_64-pc-linux-gnu/etc/python:/tmp/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython:$PYTHONPATH" LD_LIBRARY_PATH="/tmp/grass_master/dist.x86_64-pc-linux-gnu/bin:/tmp/grass_master/dist.x86_64-pc-linux-gnu/bin:/tmp/grass_master/dist.x86_64-pc-linux-gnu/scripts:/tmp/grass_master/dist.x86_64-pc-linux-gnu/lib:/tmp/grass_master/dist.x86_64-pc-linux-gnu/lib:/usr/local/lib" LC_ALL=C LANG=C LANGUAGE=C /tmp/grass_master/dist.x86_64-pc-linux-gnu/scripts/t.rast.sample --html-description < /dev/null | grep -v '</body>\|</html>' > t.rast.sample.tmp.html ; fi
Traceback (most recent call last):
  File "/tmp/grass_master/dist.x86_64-pc-linux-gnu/scripts/t.rast.sample", line 81, in <module>
    import grass.script as gscript
  File "/tmp/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/__init__.py", line 4, in <module>
    import six
ImportError: No module named six
make: *** [../..//include/Make/Html.make:14: t.rast.sample.tmp.html] Error 1
rm t.rast.sample.tmp.html
```

I assume it needs python. Its not clear to me which python version should be installed. When I try python3 any pip3 packages aren't picked up. So for example `apt install python3-debian python3-pip && pip3 install six` doesn't fix the issue.

python2 however does seem to work but fails for another reason which seems to be python2 incompatible package.


```bash
apt install -y curl && \
  curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py && \
  python2 get-pip.py

pip2 install six

# ...

  File "/tmp/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/vector/basic.py", line 9, in <module>
    from collections.abc import Iterable
ImportError: No module named abc
make: *** [../..//include/Make/Html.make:14: t.rast.sample.tmp.html] Error 1
rm t.rast.sample.tmp.html
```

looking into this `from collections.abc import Iterable` seems to be that this is compatible with python3. See: https://stackoverflow.com/questions/55882715/difference-between-from-collections-import-container-and-from-collections-abc-im

**Comment by mmacata** [comment]
Hi @sabman thanks for looking into this! The install part you found will definitely help.The other behaviour seems odd. We don't support python2 any more, in the beginning of actinia it was still used for the GRASS GIS parts inside which relates to the `t.rast.sample` error you described above.

**Comment by Momen-Mawad** [comment]
As @sabman mentioned:
> I'm running into issues at https://github.com/mundialis/actinia_core/blob/main/docs/docs/installation.md?plain=1#L80-L85 Seems to be some compatibility issues with python version. I'm investigating.

I received an error on this step also:
`/usr/bin/env: ‘python’: No such file or directory`
It is indeed a python related issue.

Following the suggested solution found here:
https://askubuntu.com/questions/942930/usr-bin-env-python-no-such-file-or-directory
I get this error no more.

The user can run the command `sudo apt-get install python-is-python3`

I shall continue with the installation steps and investigate if I will run with any further errors.
