### ISSUE TITLE
Limit of 1000 processes in process chain

### ISSUE THREAD

**Issue by jonas-eberle** [mundialis/actinia_core#237]
Hi all, 

I wanted to register 150 Sentinel-2 scenes with all their bands resulting in 2200 files to register. I used an actinia process chain using the r.external module to register this data. 

As we have 2200 files = 2200 r.external processes, an error was raised by actinia as there is a limit of 1000 processes in a processing chain: `AsyncProcessError: Process limit exceeded, a maximum of 1000 processes are allowed in the process chain.`. 

Of course I can split this into multiple calls of processing chains, but ideally I do not want to care about handling this on my own. 

What is the best and easiest way for such kind of data registration processes? 

Actinia version: 1.0.3.79. 

Thanks
Jonas

**Comment by jonas-eberle** [comment]
Hi @mmacata,

thanks for the explanation and example how to update this limit. Is there a way to configure this setting to be unlimited (0 or -1)?

I think it would be good if they (not only process_num_limit, but also cell_limit and process_time_limit) can be configured with an own default value when deploying the service.

**Comment by mmacata** [comment]
Hi @jonas-eberle,

there is no way to configure it as unlimited.

I created a MR for the user limits: https://github.com/mundialis/helm-charts/pull/10
