### ISSUE TITLE
Create importer for Sentinel data from different data source

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#242]
Currently, main Sentinel-2 import done with importer uses google cloud sources in combination with  Google BigQuery Sentinel-2 database. As therefore google credentials are needed which we don't want to add to every deployment, a different approach is wanted.

**Comment by mmacata** [comment]
Open to discussion, if we change existing functionality or if we create a new option next to it.

**Comment by griembauer** [comment]
The implementation based on Google Cloud Storage (without Google Login) is being implemented here: https://github.com/mundialis/actinia_core/pull/295
