### ISSUE TITLE
User management: allow users to know what resources they have available

### ISSUE THREAD

**Issue by veroandreo** [mundialis/actinia_core#265]
Currently if users want to know which endpoints/commands they can use, they are not able to. Only admins can, as pointed out here: https://github.com/mundialis/actinia_core/blob/a53f48fa0cfbfc926789509260981a8e0ea913e3/src/actinia_core/endpoints.py#L211 which points to: https://github.com/mundialis/actinia_core/blob/a53f48fa0cfbfc926789509260981a8e0ea913e3/src/actinia_core/rest/user_management.py#L125

Question: Could users be enabled to see their own resources/permissions/enabled modules?

**Comment by griembauer** [comment]
Hi @veroandreo, 
from version 2.0.0 on, users can query all mapsets they have access to at once using the `/mapsets` endpoint, see also https://github.com/mundialis/actinia_core/pull/249.
actinia.mundialis.de is currently still on version 1.2.1, but will be updated soon.

However using endpoints such as `/grass_modules`, `/actinia_modules`, `/modules` currently only shows **all** modules and not only the ones the user is allowed to access. You are right that this should be fixed.

**Comment by mmacata** [comment]
(waiting for deployment to be able to test)

**Comment by anikaweinmann** [comment]
TODO: 
- User should be able to request his own user
