### ISSUE TITLE
Error when attempting to create locations and mapsets

### ISSUE THREAD

**Issue by veroandreo** [mundialis/actinia_core#266]
Hi, 

I try to create a new location and mapset as this is currently needed to create STRDS (#264). However, both using actinia endpoints and `ace`, I get errors like:
 ```
 echo '{
   "epsg": "4326"
 }' > /tmp/pc_location_epsg4326.json

curl ${AUTH} -H "Content-Type: application/json" -X POST "${actinia}/api/v1/locations/latlong_TEST" -d @/tmp/pc_location_epsg4326.json
{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}
```
and
```
ace create_location="vero 4326"
Trying to create location vero
{'message': 'The server could not verify that you are authorized to access the '
            'URL requested. You either supplied the wrong credentials (e.g. a '
            "bad password), or your browser doesn't understand how to supply "
            'the credentials required.'}

ace location=latlong_wgs84 create_mapset=vero
Trying to create mapset vero
{'message': 'The server could not verify that you are authorized to access the '
            'URL requested. You either supplied the wrong credentials (e.g. a '
            "bad password), or your browser doesn't understand how to supply "
            'the credentials required.'}
```
Is this a permission problem? Is it possible for a user to create a location and mapset? I exported my credentials as env vars and they are fine.

**Comment by veroandreo** [comment]
Hi @griembauer, I see. I'm using actinia.mundialis.de, username: veroandreo. But I do not know what permissions/resources I have or not (#265). What is the role:user allowed to do?

Are there any plans to create different user levels then? Or users with the role:user must request admins to create location and mapsets and install grass addons (https://github.com/mundialis/ace/issues/6) for them?

**Comment by mmacata** [comment]
Waiting for implementation of comment above

**Comment by anikaweinmann** [comment]
Will be changed in actinia_core version > 4.2.0

**Comment by juleshaas** [comment]
The user is now allowed to create and delete own mapsets and locations via the respective endpoints. The actinia core version must be > 4.2.0.
