### ISSUE TITLE
Allow more GRASS `t.*` modules

### ISSUE THREAD

**Issue by metzm** [mundialis/actinia_core#271]
Currently, only a very limited set of GRASS `t.*` modules is allowed in https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/core/common/config.py#L45. It would be very useful, e.g. for the openEO GRASS backend, to allow more, if not all GRASS `t.rast.*` modules by default.

@mmacata @anikaweinmann There must be a reason for this relatively short whitelist?

**Comment by mmacata** [comment]
@veroandreo which modules for vector and imagery processing would you like to have included?

**Comment by veroandreo** [comment]
Assuming the user is allowed to use the endpoint to download and import landsat and/or sentinel imagery, I'd add: 
i.group, i.pansharpen, i.tasscap, i.segment, i.colors.enhance, i.cluster, i.gensig, i.maxlik, i.landsat.toar, i.atcorr (these are core modules that I commonly used within grass when working with imagery).

And for vector, as I mostly use vectors to query raster data, I'd add: v.what.rast, v.rast.stats, v.what.strds, v.db.select, v.db.update, v.db.univar, v.select, v.overlay, v.patch, v.dissolve, v.clean

**Comment by anikaweinmann** [comment]
The whitelist should be configurable and added to the config.
To default whitelist should added:
-  t.rast.aggregate, t.rast.aggregate.ds, t.rast.accumulate, t.rast.accdetect, t.rast.algebra, t.rast.what, t.rast.gapfill, t.rast.aggr_func,  t.create, t.register, t.list, t.remove, t.unregister
- v.what.rast, v.rast.stats, v.what.strds, v.db.select, v.db.update, v.db.univar, v.select, v.overlay, v.patch, v.dissolve, v.clean
- i.group, i.pansharpen, i.tasscap, i.segment, i.colors.enhance, i.cluster, i.gensig, i.maxlik, i.landsat.toar, i.atcorr

**Comment by neteler** [comment]
> Which module is t.rast.aggr_func?

AFAIK it has been renamed to
https://github.com/mundialis/openeo-addons/tree/master/t.rast.udf

**Comment by anikaweinmann** [comment]
Will be deployt with actinia-core >= 4.1.0
