### ISSUE TITLE
docker-compose build: ERROR: Service 'actinia-core' failed to build

### ISSUE THREAD

**Issue by neteler** [mundialis/actinia_core#29]
Running `docker-compose build` on a new root server (Fedora 29) led to this error:

```
...
Installed /usr/local/lib/python3.6/dist-packages/actinia_statistic_plugin-0.0.post0.dev9+g121813d-py3.6.egg
Processing dependencies for actinia-statistic-plugin==0.0.post0.dev9+g121813d
Finished processing dependencies for actinia-statistic-plugin==0.0.post0.dev9+g121813d
 ---> 2e4c507fbdda
Removing intermediate container 66e3a857c718
Step 21/51 : WORKDIR /src
 ---> 84ef6ff7b79b
Removing intermediate container faa8663af9ed
Step 22/51 : RUN git clone https://huhabla@bitbucket.org/huhabla/d_rast_multi.git d.rast.multi
 ---> Running in c00ec409aa9d
Cloning into 'd.rast.multi'...
 ---> a4c805d2bace
Removing intermediate container c00ec409aa9d
Step 23/51 : RUN grass --tmp-location EPSG:25832 --exec g.extension -s extension=d.rast.multi url=/src/d.rast.multi
 ---> Running in a11278bcab78
Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
ERROR: FileNotFoundError(2, 'No such file or directory')
Exiting...
ERROR: Service 'actinia-core' failed to build: The command '/bin/bash -c grass --tmp-location EPSG:25832 --exec g.extension -s extension=d.rast.multi url=/src/d.rast.multi' returned a non-zero code: 1
[20:12:19][STAGING][mundialis@calc2:~/repos/actinia_core/docker]$
```

This did not fail 3 hs ago on a different system, not sure what changed in actinia_core?

**Comment by mmacata** [comment]
This fails before actinia-core is cloned, so it can't be related to any changes from within actinia-core. Also it uses mundialis/grass-py3-pdal as base image which didn't change for days, so this also can't be the reason. Left are system related reasons. Which docker / docker-compose version is used?

**Comment by neteler** [comment]
The problem is here:
https://trac.osgeo.org/grass/ticket/3841

```
fd = codecs.open(os.path.join(dbase, location, 'PERMANENT', 'MYNAME'),
	                         encoding='utf-8', mode='w')
```
No idea what's wrong...

**Comment by neteler** [comment]
ok, the reason is a crash of g.proj, hence the tmp location isn't created properly.

Analysis ongoing in trac, keeping it open here until solved in main GRASS GIS.

**Comment by neteler** [comment]
So, found it:

` -march=native` for gcc is evil!

Fixed on Dockerfile:
 https://github.com/mundialis/grass-py3-pdal/commit/b7b4058a9e52a0a08dca5b819831b54583dcbacc

Docker image rebuilding is running...

**Comment by neteler** [comment]
Works, closing.
