### ISSUE TITLE
Adjust path for actinia with v3

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#292]
History from `v1` -> `v2`:

1. Change URL Prefix in actinia core DONE ✓

2. Find all occurences in code/documentation + Change

- Dokumentation umbenennen api/v1 -> api/v2 ✓
- In response Schema examples umbenennen ✓
- Ideal URL_PREFIX nutzen (actinia_core.core.common.app) ✓
- https://github.com/search?q=org%3Amundialis+api%2Fv1&type=code ✓

3. Occurences DONE: ✓

- mundialis/helm-charts https://github.com/mundialis/helm-charts/pull/11
- mundialis/actinia_core https://github.com/mundialis/actinia_core/pull/277
- mundialis/actinia-stac-plugin https://github.com/mundialis/actinia-stac-plugin/pull/41
- mundialis/actinia-module-plugin https://github.com/mundialis/actinia-module-plugin/pull/14
- mundialis/actinia-metadata-plugin https://github.com/mundialis/actinia-metadata-plugin/pull/5
- mundialis/actinia_statistic_plugin https://github.com/mundialis/actinia_statistic_plugin/pull/6
- mundialis/actinia_satellite_plugin https://github.com/mundialis/actinia_satellite_plugin/pull/8
- mundialis/ace -> über Umgebungsvariable https://github.com/mundialis/ace/pull/7
- actinia-assets actinia-assets/-/merge_requests/142
- mundialis/actinia-gdi -> egal ✓
- QGIS Plugin actiniaconnector/-/merge_requests/5 ✓

Now update from `v2` -> `v3`:

- Check above steps 1-3
- Document list what needs to be adjusted for api version update (as above list was reduced by reusing variables)
- use variables in tutorial / markdown (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#code-execution-variables--templating)

**Comment by anikaweinmann** [comment]
For step 3:
- [actinia-core](https://github.com/mundialis/actinia_core/pull/296)
- [ace](https://github.com/mundialis/ace/pull/8)

TODO
- helm-charts
- actinia-stac-plugin
- actinia-module-plugin
- actinia-metadata-plugin
- actinia_statistic_plugin
- actinia_satellite_plugin
- actinia-assets
- actinia-gdi
- QGIS Plugin
