### ISSUE TITLE
Bug: GET /grass_modules

### ISSUE THREAD

**Issue by cwhite911** [mundialis/actinia_core#384]
The GET */grass_modules* route is no longer behaving as expected after updating [actinia_core](https://github.com/mundialis/actinia_core) from v4.2.1 to v4.3.0 and [actinia_module_plugin](https://github.com/mundialis/actinia-module-plugin) from v2.3.1 to v2.4.0. The route now hangs leaving a temporary location, such as, `location_for_listing_modules_4ac35907-cc15-4832-a945-d5459c966f9d` as an artifact.

From the light debugging I've done so far, the issue does not seem to stem from the **actinia_module_plugin (v2.4.0)** because if I only update the actinia_module_plugin to v2.4.0 and leave actinia_core at v4.2.1, everything works as expected. So, it appears like something in the **actinia_core (v4.3.0)** is causing the issue, maybe with modifications to EphemeralProcessing (#380).

Let me know if I can provide you with anything else to help debug.

**Comment by ninsbl** [comment]
I am experiencing the same.

**Comment by marcjansen** [comment]
If this is adressed, a regression test would be much appreciated. My 2cents

**Comment by juleshaas** [comment]
Addressed in #388.
Fixed in actinia core version 4.3.1 and higher.
