### ISSUE TITLE
Possible to send signal on finished processing?

### ISSUE THREAD

**Issue by ninsbl** [mundialis/actinia_core#385]
For longer running processes, it would be nice if actinia could send a signal "Done" to e.g. email, some chat platform (like e.g. slack) or some other API. If workflows are run as cron-jobs for example users would interact with the API, but rather rely on notification...

As a very simple implementation I could imagine a "g.send.signal" module to be added at the end of a workflow. An alternative is to set up another cron-job for polling the status of a job, but then the cron jobs have to communicate...

**Comment by marcjansen** [comment]
We have the option of webhooks, if I remember correctly. Maybe @mmacata can provide a link to documentation?

**Comment by ninsbl** [comment]
Thanks for the hint, @marcjansen !

Thanks to this, I found: https://github.com/mundialis/actinia_core/blob/main/scripts/webhook-server

If there is additional information that would be great.

**Comment by neteler** [comment]
> If there is additional information that would be great.

Not a nice tutorial yet, but likely giving some insights: the related test:
https://github.com/mundialis/actinia_core/blob/main/tests/test_webhook.py

**Comment by neteler** [comment]
I have added this here:

https://github.com/mundialis/actinia_core/wiki#qa-using-actinia
