### ISSUE TITLE
docker failed to build

### ISSUE THREAD

**Issue by albhasan** [mundialis/actinia_core#51]
Good afternoon,

I'm having touble while building the docker image. I'm running the following:

``git clone https://github.com/mundialis/actinia_core.git``
``cd actinia_core/docker/``
``docker-compose build``
``sudo docker-compose build``

and I'm getting the following error:

``Step 21/43 : COPY docker/actinia-core/snap /src/snap``
``ERROR: Service 'actinia-core' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder473168139/docker/actinia-core/snap: no such file or directory``

I'm running    Ubuntu 18.04.3 LTS with Docker version 18.09.7, build 2d0083d

Kind regards,

**Comment by mmacata** [comment]
Hi,
we updated the Dockerfile recently but forgot to update the docker-compose.yaml. Thank you for pointing us to this!
I created a PR #52 which should fix this issue. If you like, you can test with:

```
git clone https://github.com/mmacata/actinia_core.git
cd actinia_core
git checkout docker-compose-context
cd docker
docker-compose build
sudo docker-compose build
```

**Comment by albhasan** [comment]
Hi, 
your workaround did the job! Now I'm gonna test it in my local environment. I'm very excited about Actinia and its future releases. Thanks!
