### ISSUE TITLE
Add actinia logo to git

### ISSUE THREAD

**Issue by tilladams** [mundialis/actinia_core#6]
add the actinia logo to starting page and include it in the source code. 
Thanks!

**Comment by wenzeslaus** [comment]
Hi, I want to mention Actinia in a presentation and a need some graphics for the slide. Having the logo would be great. Thanks.

**Comment by neteler** [comment]
Added to docs/
 * actinia_logo.png
 * actinia_logo_trans.png

**Comment by wenzeslaus** [comment]
Thanks. I guess I should have mentioned that before, but SVG would suite me much better, so I can stretch it on the slide as much as I need.

**Comment by neteler** [comment]
It is the preliminary Logo but better than nothing :-)

**Comment by wenzeslaus** [comment]
Thanks. Here is the result:

https://wenzeslaus.github.io/grass-gis-talks/ncgis2019_getting_started.html#/16
